#pragma once

#include <cstdint>
#include <optional>

namespace ChiyanMap::WorldGen {

// The profile is deliberately explicit. Rules for another Bedrock release must
// be added as a separate profile instead of silently sharing 26.20 constants.
enum class WorldGenProfile : std::uint8_t {
    Bedrock2620,
};

enum class Dimension : std::int8_t {
    Overworld = 0,
    Nether    = 1,
    End       = 2,
};

// This is the complete planned seed-map surface. Entries can exist in the
// catalog before their generator rule is approved, but only fixture-verified
// entries are allowed to emit map markers.
enum class LayerId : std::uint8_t {
    Village,
    PillagerOutpost,
    DesertPyramid,
    JungleTemple,
    SwampHut,
    Igloo,
    WoodlandMansion,
    OceanMonument,
    OceanRuin,
    Shipwreck,
    BuriedTreasure,
    RuinedPortal,
    RuinedPortalNether,
    Stronghold,
    Mineshaft,
    AncientCity,
    TrailRuins,
    TrialChambers,
    NetherFortress,
    BastionRemnant,
    NetherFossil,
    EndCity,
    EndGateway,
    OverworldBiomes,
    NetherBiomes,
    EndBiomes,
    SlimeChunks,
    OverworldOres,
    NetherOres,
    OverworldUndergroundFeatures,
    DungeonSpawner,
    WorldSpawn,
    MushroomFields,
    CherryGrove,
    Badlands,
    IceSpikes,
    MangroveSwamp,
    PaleGarden,
    SoulSandValley,
    CrimsonForest,
    WarpedForest,
    BasaltDeltas,
    EndSmallIslands,
    EndMidlands,
    EndHighlands,
    EndBarrens,
};

enum class LayerSupportState : std::uint8_t {
    // A Bedrock 26.20 golden fixture validates both the rule and its output.
    FixtureVerified,

    // The local cubiomes-viewer-bedrock 26.20 implementation can calculate a
    // seed prediction, although a real Bedrock /locate fixture has not yet
    // approved every output coordinate.
    CubiomesReference,

    // The deterministic placement code exists, but no controlled Bedrock
    // fixture has approved it yet. This state intentionally produces no map
    // markers.
    AlgorithmAwaitingFixture,

    // No safe local generator rule is available yet.
    Unavailable,
};

enum class PlacementAlgorithm : std::uint8_t {
    None,
    CubiomesFinder,
    LegacyBedrockMtGrid,
    Java48Grid,
    BiomeNoise,
    ChunkPopulation,
    SpawnSearch,
};

enum class QueryStatus : std::uint8_t {
    Ok,
    SeedUnavailable,
    InvalidBounds,
    DimensionMismatch,
    LayerUnavailable,
    CoordinateOverflow,
};

enum class MarkerKind : std::uint8_t {
    // A deterministic structure-start attempt. It is never a claim that the
    // structure actually generated.
    PlacementCandidate,

    // A representative point in a contiguous rare-biome region generated by
    // cubiomes from the world seed.
    BiomeRegion,
};

// A remote Bedrock server that does not disclose its seed exposes this value
// through the client level API. It is a protocol placeholder, not a world
// seed that can be used for deterministic structure placement.
inline constexpr std::uint64_t kUnavailableRemoteBedrockSeedBits = 0x00000000FFFFFFFFULL;

[[nodiscard]] constexpr bool IsUsableCapturedBedrockSeed(std::uint64_t seedBits) noexcept {
    return seedBits != kUnavailableRemoteBedrockSeedBits;
}

// Carries the bit-exact world seed captured from the level. `0` is a valid
// captured seed; `HasSeed() == false` is the only read-failure representation.
class SeedSnapshot final {
public:
    constexpr SeedSnapshot() noexcept = default;

    [[nodiscard]] static constexpr SeedSnapshot Unavailable() noexcept {
        return SeedSnapshot{};
    }

    [[nodiscard]] static constexpr SeedSnapshot FromLevelSeed(std::int64_t levelSeed) noexcept {
        return SeedSnapshot{true, static_cast<std::uint64_t>(levelSeed)};
    }

    // Use this overload when a host API already exposes the seed as raw bits.
    [[nodiscard]] static constexpr SeedSnapshot FromSeedBits(std::uint64_t seedBits) noexcept {
        return SeedSnapshot{true, seedBits};
    }

    [[nodiscard]] constexpr bool HasSeed() const noexcept {
        return hasSeed_;
    }

    [[nodiscard]] constexpr std::optional<std::uint64_t> TrySeedBits() const noexcept {
        return hasSeed_ ? std::optional<std::uint64_t>{seedBits_} : std::nullopt;
    }

    // The legacy Bedrock RNG path intentionally receives only the low 32 bits.
    [[nodiscard]] constexpr std::optional<std::uint32_t> TryLegacySeed32() const noexcept {
        return hasSeed_ ? std::optional<std::uint32_t>{static_cast<std::uint32_t>(seedBits_)} : std::nullopt;
    }

    [[nodiscard]] constexpr bool operator==(const SeedSnapshot&) const noexcept = default;

private:
    constexpr SeedSnapshot(bool hasSeed, std::uint64_t seedBits) noexcept : hasSeed_(hasSeed), seedBits_(seedBits) {}

    bool          hasSeed_  = false;
    std::uint64_t seedBits_ = 0;
};

struct ChunkPosition final {
    std::int64_t x = 0;
    std::int64_t z = 0;

    [[nodiscard]] constexpr bool operator==(const ChunkPosition&) const noexcept = default;
};

struct BlockPosition final {
    std::int64_t x = 0;
    std::int64_t z = 0;

    [[nodiscard]] constexpr bool operator==(const BlockPosition&) const noexcept = default;
};

// The upper edges are exclusive. Half-open bounds let adjacent map tiles meet
// without sharing a marker on their border.
struct BlockRect final {
    std::int64_t minX = 0;
    std::int64_t minZ = 0;
    std::int64_t maxXExclusive = 0;
    std::int64_t maxZExclusive = 0;

    [[nodiscard]] constexpr bool IsValid() const noexcept {
        return minX < maxXExclusive && minZ < maxZExclusive;
    }

    [[nodiscard]] constexpr bool Contains(BlockPosition point) const noexcept {
        return point.x >= minX && point.x < maxXExclusive && point.z >= minZ && point.z < maxZExclusive;
    }
};

// A read-only query value suitable for copying onto a worker thread. It never
// owns game objects, level references, or chunk references.
class LayerQuery final {
public:
    constexpr LayerQuery(
        SeedSnapshot    seed,
        WorldGenProfile profile,
        Dimension       dimension,
        LayerId         layer,
        BlockRect       bounds
    ) noexcept
    : seed_(seed), profile_(profile), dimension_(dimension), layer_(layer), bounds_(bounds) {}

    [[nodiscard]] constexpr const SeedSnapshot& Seed() const noexcept {
        return seed_;
    }

    [[nodiscard]] constexpr WorldGenProfile Profile() const noexcept {
        return profile_;
    }

    [[nodiscard]] constexpr Dimension TargetDimension() const noexcept {
        return dimension_;
    }

    [[nodiscard]] constexpr LayerId Layer() const noexcept {
        return layer_;
    }

    [[nodiscard]] constexpr const BlockRect& Bounds() const noexcept {
        return bounds_;
    }

private:
    SeedSnapshot    seed_;
    WorldGenProfile profile_;
    Dimension       dimension_;
    LayerId         layer_;
    BlockRect       bounds_;
};

// Immutable output. Coordinates identify the placement attempt's chunk and
// its conventional map anchor (chunk origin + 8 in each horizontal axis).
class SeedMapMarker final {
public:
    constexpr SeedMapMarker(
        LayerId       layer,
        Dimension     dimension,
        ChunkPosition chunk,
        BlockPosition block,
        MarkerKind    kind = MarkerKind::PlacementCandidate
    ) noexcept
    : layer_(layer), dimension_(dimension), chunk_(chunk), block_(block), kind_(kind) {}

    [[nodiscard]] constexpr LayerId Layer() const noexcept {
        return layer_;
    }

    [[nodiscard]] constexpr Dimension TargetDimension() const noexcept {
        return dimension_;
    }

    [[nodiscard]] constexpr ChunkPosition Chunk() const noexcept {
        return chunk_;
    }

    [[nodiscard]] constexpr BlockPosition Block() const noexcept {
        return block_;
    }

    [[nodiscard]] constexpr MarkerKind Kind() const noexcept {
        return kind_;
    }

    constexpr SeedMapMarker(const SeedMapMarker&) noexcept            = default;
    constexpr SeedMapMarker(SeedMapMarker&&) noexcept                 = default;
    constexpr SeedMapMarker& operator=(const SeedMapMarker&) noexcept = default;
    constexpr SeedMapMarker& operator=(SeedMapMarker&&) noexcept      = default;

private:
    LayerId       layer_;
    Dimension     dimension_;
    ChunkPosition chunk_;
    BlockPosition block_;
    MarkerKind    kind_ = MarkerKind::PlacementCandidate;
};

struct MarkerKey final {
    LayerId       layer{};
    Dimension     dimension{};
    ChunkPosition chunk{};

    [[nodiscard]] constexpr bool operator==(const MarkerKey&) const noexcept = default;
};

[[nodiscard]] constexpr MarkerKey GetMarkerKey(const SeedMapMarker& marker) noexcept {
    return MarkerKey{marker.Layer(), marker.TargetDimension(), marker.Chunk()};
}

[[nodiscard]] constexpr bool IsMarkerEmissionAllowed(LayerSupportState support) noexcept {
    return support == LayerSupportState::FixtureVerified
        || support == LayerSupportState::CubiomesReference;
}

} // namespace ChiyanMap::WorldGen
